# Generated by Django 5.0.2 on 2024-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0003_alter_aset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
